#############################
## Configuration for lsp-ai ##
##############################
[language-server.lsp-ai]
command = "lsp-ai"
timeout = 60

[language-server.lsp-ai.config.memory]
file_store = { }

# [language-server.lsp-ai.config.models.model1]
# type = "ollama"
# model = "deepseek-coder"

[language-server.lsp-ai.config.models.model1]
type = "mistral_fim"
fim_endpoint = "https://api.mistral.ai/v1/fim/completions"
model = "codestral-latest"
auth_token_env_var_name = "MISTRAL_API_KEY"

# [language-server.lsp-ai.config.models.model1]
# type = "open_ai"
# completions_endpoint = "https://chat.interlogica.lan:4443/api/chat/completions"
# model = "claude-sonnet-4-20250514"
# auth_token_env_var_name = "IL_AI_KEY"

[language-server.lsp-ai.config.completion]
model = "model1"

[language-server.lsp-ai.config.completion.parameters]
max_tokens = 64
max_context = 1024
temperature = 0.2
system = "You are a code assistant chatbot specialized in Go, Typescript, CSS, Html, angular, react, vue. The user will ask you for assistance coding and you will do your best to answer succinctly and accurately"

[language-server.lsp-ai.config.completion.parameters.fim]
start = "<fim_prefix>"
middle = "<fim_suffix>"
end = "<fim_middle>"


###################################
## Configuration for lsp-angular ##
###################################

[language-server.angular]
command = "ngserver"
args = [
  "--stdio",
  "--tsProbeLocations",
  "/home/paoloc/.local/share/mise/installs/npm-typescript/latest/lib",
  "--ngProbeLocations",
  "/home/paoloc/.local/share/mise/installs/npm-angular-language-server/latest/bin"
  ]

#######################################################
## Configuration for vscode-html/css/ts lsp with mise##
#######################################################
[language-server.typescript-language-server.config.tsserver]
path = "/home/paoloc/.local/share/mise/installs/npm-typescript/latest/lib/node_modules/typescript/lib"
[language-server.typescript-language-server.config.css-languageserver]
path = "/home/paoloc/.local/share/mise/installs/npm-vscode-css-languageserver-bin/latest/lib"



[language-server.mpls]
command = "mpls"
args = ["--dark-mode", "--enable-emoji"]

[[language]]
name = "go"
language-servers = [ "gopls", "golangci-lint-lsp", "lsp-ai" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "markdown-oxide", "mpls" ]

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "lsp-ai" ]
auto-format = true
