# in <config_dir>/helix/languages.toml
[language-server.sql-lsp]
command = "sql-language-server"
args = ["up", "--method stdio"]

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "tsx"
auto-format = true

[[language]]
name = "sql"
language-servers = [ "sql-lsp" ]
formatter = [ "sql-formatter" ]
auto-format = true
