# in <config_dir>/helix/languages.toml
[language-server.sql-lsp]
command = "sql-language-server"
args = ["up", "--method stdio"]

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]
config = { provideFormatter = true, css = { validate = { enable = true } } }

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]
config = { provideFormatter = true  }

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]
config = { provideFormatter = true, css = { validate = { enable = true } } }


[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "tsx"
auto-format = true

[[language]]
name = "sql"
language-servers = [ "sql-lsp" ]
formatter = [ "sql-formatter" ]
auto-format = true
