# in <config_dir>/helix/languages.toml
# [language-server.angular]
# command = "ngserver"
# args = [
#   "--stdio",
#   "--tsProbeLocations",
#   "/home/paoloc/.local/share/mise/installs/npm-typescript/latest/lib",
#   "--ngProbeLocations",
#   "/home/paoloc/.local/share/mise/installs/npm-angular-language-server/latest/bin"
#   ]

[language-server.typescript-language-server.config.tsserver]
path = "/home/paoloc/.local/share/mise/installs/npm-typescript/latest/lib/node_modules/typescript/lib"

[language-server.sql-lsp]
command = "sql-language-server"
args = ["up", "--method stdio"]

[language-server.vscode-css-language-server]
command = "css-languageserver"
args = ["--stdio"]
config = { provideFormatter = true, css = { validate = { enable = true } } }

[language-server.vscode-html-language-server]
command = "html-languageserver"
args = ["--stdio"]
config = { provideFormatter = true, css = { validate = { enable = true } } }

[language-server.vscode-json-language-server]
command = "vscode-json-languageserver"
args = ["--stdio"]
config = { provideFormatter = true, css = { validate = { enable = true } } }


[[language]]
name = "html"
# language-servers = [ "angular", "html-languageserver" ]
language-servers = [  "html-languageserver" ]
auto-format = true

[[language]]
name = "typescript"
# language-servers = [ "angular", "typescript-language-server" ]
language-servers = [ "typescript-language-server" ]
language-id = "typescript"
file-types = ["ts", "mts", "cts"]
auto-format = false

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server" ]
file-types = ["tsx"]
auto-format = true

[[language]]
name = "sql"
language-servers = [ "sql-lsp" ]
formatter = [ "sql-formatter" ]
auto-format = true
