[tools]
fd = "latest"
glow = "latest"
helix = "latest"
lazygit = "latest"
starship = "latest"
yazi = "latest"
zellij = "latest"
bat = "latest"
difftastic = "latest"
aws-cli = "latest"
fastfetch = "latest"
superhtml = "latest"
pipx = "latest"
"pipx:tldr" = "latest"
pnpm = "latest"
opencode = "latest"

[settings]
experimental = true
